recipe_parameters:
  - name: cutting_speed
    type: float
    description: "Surface speed in m/min"
  - name: feedrate_fu
    type: float
    description: "Feed rate in mm/rev"
  - name: cut_depth
    type: float
    description: "Depth of cut in mm"
  - name: cut_width
    type: float
    description: "Width of cut in mm"
  - name: pecking_depth
    type: float
    description: "Pecking depth for drilling"
  - name: lifetime
    type: float
    description: "Tool lifetime in minutes"
  - name: coolant
    type: string
    description: "Coolant type"
  - name: airblast
    type: string
    description: "Airblast status"
  - name: ramping_angle
    type: float
    description: "Ramping angle for helical milling"
  - name: comments
    type: string
