tool_parameters:
  - name: diameter
    type: float
    description: "Tool diameter in mm"
  - name: number_of_flutes
    type: int
    description: "Number of flutes on tool"
  - name: tool_designation
    type: string
    description: "Designation code for tool"
  - name: insert_designation
    type: string
    description: "Designation code for insert"
  - name: vendor
    type: string
    description: "vendor of tool"
  - name: tool_comments
    type: string
    description: "General info / comment"